remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme # Add this if missing

title: "Long Reply"
description: "Sharing Long-Form Content with GitHub Pages"
baseurl: "/longreply" # If this is a project repo
url: "https://leebase.github.io"