remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

title: "Long Reply"
description: "Sharing Long-Form Content with GitHub Pages"
baseurl: "/longreply"  # IMPORTANT: This must match your repo name
url: "https://leebase.github.io"

collections:
  pages:
    output: true